config/routes.rb
TwitterForZombies::Application.routes.draw do

  resources "tweets"
  resources "zombies"
  
  root :to => "tweets#index"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :zombie
  attr_accessible :status, :zombie
  validates_presence_of :status, :zombie
  validates_associated :zombie
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  attr_accessible :name, :graveyard
  has_many :tweets
  validates_presence_of :name, :graveyard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_filter :get_tweet, :only => [:edit, :update, :destroy]

  def get_tweet
    @tweet = Tweet.find(params[:id])
  end

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
    @tweet.zombie = Zombie.first
  end

  def create
    if @tweet = Tweet.create(params[:tweet])
      render :show
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterForZombies</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <!-- <a class="brand" href="#">Twitter for zombies</a> -->
            <%= link_to "Twitter for zombies", root_path, :class => 'brand' %>
        </div>
    </div>
</div>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/tweets/delete.html.erb
<h1>Tweets#delete</h1>
<p>Find me in app/views/tweets/delete.html.erb</p>

app/views/tweets/edit.html.erb
<div class="container">
	<div class="row">
		<div class="span6">
			<%= form_for @tweet do |f| %>
			<p><%= f.label :from, 'From:' %><%= f.text_field :zombie_id %></p>
			<p><%= f.label :status, 'Status: ' %><%= f.text_area :status %></p>
			<%= f.submit :class => 'btn btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/tweets/index.html.erb
<div class="container">
    <div class="row"> 
        <div class="span4">
        <% if @tweets.empty? %>
            <em>No tweets found</em>
        <% else %>
            <table class="tweets">
                <tr>
                    <th>Status</th>
                    <th>Zombie</th>
                    <th></th>
                    <th></th>
                </tr>
            <% @tweets.each do |tweet| %>
                <tr>
                <td><%= tweet.status %></td>
                <td><%= link_to tweet.zombie.name, zombies_path(tweet.zombie) %></td>
                <td><%= link_to 'edit', edit_tweet_path(tweet) %></td>
                <td><%= link_to 'delete', tweet, :method => :delete %></td>
        	    </tr>
            <% end %>
            </table>
        <% end %>
        </div>
    </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
	<div class="row">
		<div class="span6 offset 2">
			<%= form_for @tweet do |f| %>
			<p><%= f.label :from, 'From:' %><%= f.label :zombie, @tweet.zombie.name %></p>
			<p><%= f.label :status, 'Status: ' %><%= f.text_area :status %></p>
			<%= f.submit :class => 'btn btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/tweets/show.html.erb
<div class="container">
    <div class="row"> 
        <div class="span4">
        <% tweets = Tweet.all %>
        <% if tweets.empty? %>
            <em>No tweets found</em>
        <% else %>
            <table class="tweets">
                <tr>
                    <th>Status</th>
                    <th>Zombie</th>
                    <th></th>
                    <th></th>
                </tr>
            <% tweets.each do |tweet| %>
                <tr>
                <td><%= tweet.status %></td>
                <td><%= link_to tweet.zombie.name, zombies_path(tweet.zombie) %></td>
                <td><%= link_to 'edit', edit_tweet_path(tweet) %></td>
                <td><%= link_to 'delete', tweet, :method => :delete %></td>
        	    </tr>
            <% end %>
            </table>
        <% end %>
        </div>
    </div>
</div>

app/views/zombies/edit.html.erb
<div class="container">
	<div class="row">
		<div class="span8">
			<% tweets = Zombie.find(params[:id]).tweets %>
            <% tweets.each do |tweet| %>
            <div class="tweet">
            	<p>From: <%= tweet.zombie.name %></p>
            	<p>Status: <%= tweet.status %></p>
        	</div>
            <% end %>
            <% if tweets.empty? %>
            	<em>No tweets found</em>
            <% end %>

		</div>
	</div>
</div>

app/views/zombies/index.html.erb
<div class="container">
	<div class="row">
		<div class="span8">
			<% zombies = Zombie.all %>
            <% zombies.each do |zombie| %>
                <div><%= link_to zombie.name, zombie %></div>
            <% end %>
            <% if zombies.empty? %>
            	<em>No zombies found</em>
            <% end %>

		</div>
	</div>
</div>

app/views/zombies/new.html.erb
<div class="container">
	<div class="row">
		<div class="span8">
			<% tweets = Zombie.find(params[:id]).tweets %>
            <% tweets.each do |tweet| %>
            <div class="tweet">
            	<p>From: <%= tweet.zombie.name %></p>
            	<p>Status: <%= tweet.status %></p>
        	</div>
            <% end %>
            <% if tweets.empty? %>
            	<em>No tweets found</em>
            <% end %>

		</div>
	</div>
</div>

app/views/zombies/show.html.erb
<div class="container">
	<div class="row">
		<div class="span8">
			<% tweets = Zombie.find(params[:id]).tweets %>
            <% tweets.each do |tweet| %>
            <div class="tweet">
            	<p>From: <%= tweet.zombie.name %></p>
            	<p>Status: <%= tweet.status %></p>
        	</div>
            <% end %>
            <% if tweets.empty? %>
            	<em>No tweets found</em>
            <% end %>

		</div>
	</div>
</div>

app/views/zombies/view.html.erb
<div class="container">
	<div class="row">
		<div class="span8">
			<% tweets = Zombie.find(params[:id]).tweets %>
            <% tweets.each do |tweet| %>
            <div class="tweet">
            	<p>From: <%= tweet.zombie.name %></p>
            	<p>Status: <%= tweet.status %></p>
        	</div>
            <% end %>
            <% if tweets.empty? %>
            	<em>No tweets found</em>
            <% end %>

		</div>
	</div>
</div>